# This is a basic workflow to help you get started with Actions

name: CI
run-name: Deploy by @${{ github.actor }}
env:
  GITHUB_ACTIONS: github_actions
# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "github-task-job"
  github-task-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - run: echo "Show the env variable ${{ env.GITHUB_ACTIONS }}"
      - run: echo "The repository name is ${{ github.repository }}. The branch name is ${{ github.ref_name }}"
      - run: echo "The workflow was launched by ${{ github.event_name }}"
